const data = [
  {
    id: 1,
    title: 'Thailand Island Hopper',
    description: 'Active Adventure, Beach, Private, Group, Fully Guided, Explorer',
    destinations: 'Bangkok, Surat Thani, Khao Sok National Park, Ko Pha Ngan, Koh Tao, Ao Nang',
    age: '18 to 39 year olds',
    price: '1,350',
    discountPercentage: 20,
    discountPrice: '1,080',
    save: 270,
    rating: 4.5,
    pricePerDay: 77,
    TourLength: 14,
    image: 'https://cdn.tourradar.com/s3/tour/645x430/67027_5dfb47423685e.jpg',
  },
  {
    id: 2,
    title: 'Sri Lanka',
    description: 'Active Adventure, Safari, Local Living, Group, Fully Guided',
    destinations: 'Negombo, Dambulla, Sigiriya, Kandy, Ella, Udawalawe National Park',
    age: '18 to 39 year olds',
    price: '1,301',
    discountPercentage: 20,
    discountPrice: '1,041',
    save: 260,
    rating: 5,
    pricePerDay: 87,
    TourLength: 12,
    image: 'https://cdn.tourradar.com/s3/tour/645x430/98680_63f9dd5654ab7.jpg',
  },
  {
    id: 3,
    title: 'Bali & Beyond',
    description: 'Private, Group, Fully Guided, Explorer',
    destinations: 'Denpasar, Canggu, Ubud, Gili Trawangan, Labuhan Lombok, Sumbawa Besar',
    age: '18 to 39 year olds',
    price: '2,195',
    discountPercentage: 30,
    discountPrice: '1,537',
    save: 658,
    rating: 5,
    pricePerDay: 85,
    TourLength: 18,
    image: 'https://cdn.tourradar.com/s3/tour/645x430/102207_4f5b1c.jpg',
  },
  {
    id: 4,
    title: 'Bangkok',
    description: 'Active Adventure, Local Living, Group, Fully Guided',
    destinations: 'Thailand, Malaysia, Singapore, Indonesia',
    age: '18 to 39 year olds',
    price: '3,129',
    discountPercentage: 15,
    discountPrice: '2,660',
    save: 469,
    rating: 5,
    pricePerDay: 99,
    TourLength: 27,
    image: 'https://cdn.tourradar.com/s3/tour/645x430/101072_5e3ce1ce15de8.jpg',
  },
];

export default data;
